### ISSUE TITLE
OpenELEC for MXQ with Amlogic S805 SoC

### ISSUE THREAD

**Issue by MasterofArts** [codesnake/OpenELEC.tv#100]
Hello There,

Would someone be kind enough to point me in the direction on getting openELEC on MXQ with Amlogic S805 SoC & how to install?

Many thanks.

**Comment by techetga** [comment]
https://github.com/kszaq/OpenELEC.tv/releases
Instructions and downloads over there

**Comment by MasterofArts** [comment]
Thanks dood
