### ISSUE TITLE
TOPIC: MXQ OPENELEC BUILD. I HAVE QUESTIONS? LOL MXQ OPENElec Build. I Have Questions? LOL

### ISSUE THREAD

**Issue by TheChangingMan** [codesnake/OpenELEC.tv#114]
Im unsure if im in the right section here lol! I cant seem to find an introduction section so here it goes LOL

Basically im a complete NEWBIE! I know basically F**k all.. So i thought id ask for my research from the main men themselves, The DEVS and Clued up peeps :)

So my questions are as follows!

I Installed an Openelec build on my MXQ Android Based Box. EXCELLENT. Runs smoothly. I know its not an official build but the work Codesnake has done is brill! What i want to know is can an Openelec build be altered? i would like to alter the splash screen to my custom image, but can this be done on a unnoficial build?

Also ive always found that the Build only runs while the SD card is inserted. Is there anyway it can be written onto the box itself without an SD?

And my third question.
Can the build itself be altered/modified so that my custom kodi build will automatically load up when i install the Openelec build.

Ive tried to do some research but cant find these awnsers. Any help is appreciated. Hopefully ive posted in the right place. If not could admins move my thead to the approprate section

Many Thanks

Dave.

**Comment by codesnake** [comment]
What build did you install?

**Comment by TheChangingMan** [comment]
S805 Openelec for MXQ

**Comment by codesnake** [comment]
I'm asking because I didn't release any builds for MXQ.

**Comment by TheChangingMan** [comment]
Oh... Amlogic S805 Chipset ?

**Comment by TheChangingMan** [comment]
Its an Android based Set Top Box

**Comment by codesnake** [comment]
Yes, I didn't release any builds for Amlogic S805.

**Comment by TheChangingMan** [comment]
Im a complete newbie lol Sorry! :)

in Simple terms.. what i would like to do is run an openelec build on a Amlogic based Android Box. But i would like to customize the build to show my own splashscreen and own build of kodi. is this possible?

**Comment by TheChangingMan** [comment]
http://forum.xda-developers.com/android/development/rom-openelec-amlogic-based-tv-boxes-t2832289

This is where i downloaded your build :)

**Comment by codesnake** [comment]
And where is the build for MXQ? It is possible to change the spash screens, but is not an issue and offtopic here.
