### ISSUE TITLE
Black screen when switching channels during Live TV

### ISSUE THREAD

**Issue by walterheisenberg** [codesnake/OpenELEC.tv#116]
This has been reported and discussed multiple times. It has not been fixed, I think, in a general way for all systems. The problem still persists. 
*) http://trac.kodi.tv/ticket/16515
trac ticket for Kodi with code to reproduce
1) ​http://forum.odroid.com/viewtopic.php?f=117&t=11869
2) ​http://trac.kodi.tv/ticket/15881
3) ​http://openelec.tv/forum/87-vdr-addon/79303-need-help-live-tv-freeze-after-a-short-play
4) http://wetekforums.com/v/index.php?p=/discussion/455/solved-black-screen-bug-thread#latest

**Comment by grin1** [comment]
I've exactly the same problem. Screen gets black, audio still playing. Log file uploaded here: http://pastebin.com/0RCxs7Xr
