### ISSUE TITLE
hi all 

### ISSUE THREAD

**Issue by nautilus1212** [codesnake/OpenELEC.tv#117]
after a long and pointless task can someone please tell me
where to get o/e file with kodi 15.2 needed for s805 cpu ARMv7
having major probs :(
many thx

**Comment by codesnake** [comment]
S805-based boxes currently is not supported here. You need to find the firmware that matches your box.

**Comment by nautilus1212** [comment]
hi
anyidea where I can find? as been looking for ages
thx
