### ISSUE TITLE
OpenELEC-amlogic.MXQ.arm-6.0.1.1 remote.conf problem

### ISSUE THREAD

**Issue by scenicguy** [codesnake/OpenELEC.tv#118]
Hi Codesnake, I have flashed the OpenELEC-amlogic.MXQ.arm-6.0.1.1 to my MXQ-S805 v1.2 (HD18O v1.2) box and all is working fine, except for the remote which only partially works. I have tried to ssh a stock remote.conf using winscp but this always fails with an error 4 failure message. I cannot edit the file in winscp either. I am not familiar with PuTTy's commands and have no idea how to get the file from my windows pc into Openelec, any help would be very much appreciated as I am very happy with Openelec, which is considerably faster than Android and way smoother.

**Comment by kszaq** [comment]
OpenELEC-amlogic.MXQ.arm-6.0.1.1 is not Codesnake's release. It's mine and you should post your question here: https://github.com/kszaq/OpenELEC.tv
