### ISSUE TITLE
TVHeadend Client

### ISSUE THREAD

**Issue by jaarsa** [codesnake/OpenELEC.tv#119]
Why am I unable to install PVR-Clients on my MX2 board.

PVR-Clients don't show up in the list as an option.

Is it possible to download this Addon-client as a ZIP file and manually install it?

**Comment by gnickoloff** [comment]
Yeah. That's how you have to do it. Not sure if it's going to work out well for you.
[url](http://forum.kodi.tv/showthread.php?tid=258589)[/url]

**Comment by codesnake** [comment]
This isssue will be fixed in OE 6.0.1.
