### ISSUE TITLE
Tuner not found AVERTV VOLAR GREEN HD

### ISSUE THREAD

**Issue by Mizar03** [codesnake/OpenELEC.tv#123]
Hi, I've just received my M8s+ with openelec pre installed. Everything works fine but my tuners are not seen by tvheadend (AVerTV Volar Green HD). They work fie on PC or RPi2.
Does anyone knows something about this ?
Jérôme

**Comment by codesnake** [comment]
M8S+ is not supported here.

**Comment by Mizar03** [comment]
Do you know a place where it is supported ? 

Le 23-02-2016 13:31, Alex Deryskyba a écrit : 

> M8S+ is not supported here. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 

_Cordialement,_ 

_ _ 

_Stéphanie et Jérôme Gonzalez_ 

Links:
------
[1]
https://github.com/codesnake/OpenELEC.tv/issues/123#issuecomment-187681168

**Comment by codesnake** [comment]
No
