### ISSUE TITLE
s89 support

### ISSUE THREAD

**Issue by DvirYamin** [codesnake/OpenELEC.tv#136]
Hey alex,
does this version of openelec support s89 elite device?
is it support cec-hdmi?
what version of kodi it runs?

Thanks a lot,
dvir yamin

**Comment by DvirYamin** [comment]
hey codesnake please answer my question

**Comment by codesnake** [comment]
Hi DvirYamin,
No, it doesn't support any S905-based boxes yet. But most likely it will support some in future,
It supports HDMI CEC. Kodi version depends on OE version. OE 6.0 supports Kodi 15. OE 7.0 will support Kodi 16.
