### ISSUE TITLE
Possible to run full linux distribution on Amlogic boxes?

### ISSUE THREAD

**Issue by ivanholmes** [codesnake/OpenELEC.tv#143]
Hi, I was just wondering what alterations in general could be made to this image or others like it in order to make a full linux distribution. I know that OpenELEC is locked down to make it more secure and easier to support, but can this be changed i.e. making the root filesystem read-write? Where in the source can the mounting information be found?

I realise that issues may not be the best place to post this question but I don't have a freaktab account, sorry. I have tried to find information on this via google but my searches have given no useful information, even the right things to search for would be useful.

Thanks for any help you can give,
Ivan

**Comment by lavvy** [comment]
Osmc vero2

**Comment by ivanholmes** [comment]
Thanks a lot, I was unaware that the Vero 2 was an Amlogic device. Just for anyone else who reads this, OSMC is not locked down in the same way as OpenELEC so this answers my question perfectly.
