### ISSUE TITLE
mplayer for AMLogic AML-872 MX ?

### ISSUE THREAD

**Issue by bezik46** [codesnake/OpenELEC.tv#156]
Wetek Play with AMLogic AML-872 MX
Is there a compiled version of mplayer that would work on OE 8.0.4?

**Comment by bezik46** [comment]
Anybody?

**Comment by codesnake** [comment]
OpenELEC is targeted to run Kodi, running another media player alongside Kodi is overkill.

**Comment by bezik46** [comment]
Thanks, but that is not really an answer to the question, I then assume that it is not
