### ISSUE TITLE
k200 t8 openelec issue

### ISSUE THREAD

**Issue by gabs777** [codesnake/OpenELEC.tv#17]
Hello friend, I have attempted many times to install the m8 OE build from your forum post onto a t8 box without success. I have flashed many boxes before so am sure I am doing it correctly. I cannot even get to recovery screen all I see is 'no signal'. When I release the toothpick box boots into stock firmware. I know that you are working on OE build for t8, but I have been told that this current m8 build will work on the t8. Do you have any advice as to what the issue is, or could you send me direct link to correct file as, I fear I may be using the incorrect file.
Thanks, Gabs...

**Comment by f4rell09** [comment]
hello codesnake,are you planning on making an openelec version for T8 single wifi or dual wifi??thank you.
