### ISSUE TITLE
4.97.3 doesn't boot on MX2 after a couple of reboots

### ISSUE THREAD

**Issue by akorinek** [codesnake/OpenELEC.tv#31]
Hi,

I've been using 4.2.1 and 4.97.1 on my Matricom MX2 successfully. Now I've updated to 4.97.3 and have the following problem:
I update using the toothpick method, update is successful and I can boot the first time into kodi. There is something about "tar file found, extracting" and then "system or kernel missing, normal boot in 10s" on that first boot.

Afterwards when I switch off the device and restart it, it gets stuck on the boot screen, just says "Openelec (unofficial) - Version: 4.97.3" and that's it. To get it booting again, I need to reinstall using the toothpick method.

Can you please tell me how to fix this?

**Comment by akorinek** [comment]
I reverted back to 4.2.1 now, and have the same issue, second boot gets stuck. I get more messages though, I see "xmbc hacks failed"

**Comment by codesnake** [comment]
To help with your issue I need to reproduce it. But I cannot reproduce your probem on my MX2.

**Comment by akorinek** [comment]
Can I be of help? Can you send me some file to test or something else?

**Comment by codesnake** [comment]
Unfrotunately this is not possible.

**Comment by akorinek** [comment]
So it seems I got it fixed: There must have been some messup in the file system or something, and just wiping the system and cache didn't do the trick. I ended up installing the original MX firmware 1.1.5 and then Openelec 4.97.3. Then all my settings and movie db were actually gone and now openelec boots cleanly.

**Comment by codesnake** [comment]
Glad to hear your issue is resolved.
