### ISSUE TITLE
Meson6/WeTek.Play - hdmi audio locking issue on 1080p24 with yamaha amps

### ISSUE THREAD

**Issue by Memphiz** [codesnake/OpenELEC.tv#35]
Hey Codesnake,

i wanted to report an issue with audio locking. Basically when setting 1080p24 and passing through AC3 or DTS there is a problem that alot of yamaha amps don't lock on the audio stream. This manifests in flickering "DTS" printout and stuttered sound. Eventually it locks after 5 - 30 seconds or it may lock never. It might even disable the decoder completely and doesn't seem to even try to lock on the signal after that.

The behavior on AC3 is a bit better then on DTS but also there the locking is not stable.

This whole thing reminds me on the pivos m3 box. The same issue happened there too - see this thread for the report (thats why i assume that again alot of yamaha amps are seeing this problem - i for myself have an Yamaha RX 367):

http://www.pivosforums.com/viewtopic.php?f=25&t=1367

The solution from pivos for the M3 was to take over the audio_N_para values in hdmi_tx_hw.c (function hdmitx_m3_set_audmode) from the M1 kernel (in your aml kernel its something similar with set_audmode in it).

Those are the ones:

https://github.com/Pivosgroup/buildroot-linux-kernel-m3/blob/master/drivers/amlogic/hdmi/hdmi_tx/m3/hdmi_tx_hw.c#L2437

I t ried to use those values for the meson6/WeTek.Play aswell but had no success here. It influences the audio lock for sure - but made it even worse.

Do you know someone who has the hdmi spec and is familiar with the meson6 hardware enough to spot a bug in there or any other idea howto fix the lock problem for wetek.play? ATM i have to run it on 720p because of that (1080p50/60 has also audio lock problems - not so bad as 24hz but similar).

Thx for reading :)

**Comment by bjorn1981** [comment]
Something similar happens on rpi. There the solution is using an override in config.txt called hdmi_force_edid_audio=1 Maybe this can be implemented for Amlogic also.

**Comment by Memphiz** [comment]
i think the rbpi thing does something different then what is needed here based on the solution for the pivos m3 box ...

**Comment by Memphiz** [comment]
Found the solution:

https://github.com/Memphiz/OpenELEC.tv/commit/38eca7fee87a7cdab353e021d42c8244804a3439

Will PR against OE ...

**Comment by codesnake** [comment]
Great!
