### ISSUE TITLE
/dev/videocap0 missing on M8 build

### ISSUE THREAD

**Issue by ipodtouchdude** [codesnake/OpenELEC.tv#56]
Hi, I am running your Openelec 5.0.3 build on my M8 and /dev/videocap0 is missing. I need this so I can use boblightd with my lightpack. I know it is enabled in the kernel of your build but it is not working on the M8 for some reason. I am willing to test beta builds to help get it working as my M8 is not my main device while my lightpack does not work on it.

**Comment by irfankhani** [comment]
Brother I've Amlogic M8 Box (s802) K200 Board, brother i installed 5.0.3 and i m facing problem with bluetooth cause i have bluetooth headset and after installing openelec bluetooth headset not working kindly tell me any configuration to work bluetooth headset.

**Comment by ipodtouchdude** [comment]
According to Memphiz (Team-Kodi Developer) on the Kodi forums CONFIG_AM_VIDEOCAPTURE need to be enabled in the kernel which it is and in arch/arm/boot/dts/amlogic/meson8_k200a_2G.dtb to make it work.

**Comment by ipodtouchdude** [comment]
Managed to patch it in myself. I have also posted it on freaktab for people to download until you add support for it in your later builds. http://freaktab.com/forum/tv-player-support/amlogic-based-tv-players/eny-acemax-em8-square-em6q-etc-devices/491016-openelec-5-0-5-eny-m8-2g-square-with-amcodec-boblightd-support
