### ISSUE TITLE
IPTV Simple Client not working M8 S802 

### ISSUE THREAD

**Issue by kraigtoft** [codesnake/OpenELEC.tv#70]
Hi all

I thought i would try setting up the IPTV simple client for something to do before my tuner turns up in the post, i have set i tup like i use to do in the android version on my M8 box before i installed your Openelec on it. 

Problem: when i enable live tv in the settings it does not give the message to enable the pvr client, once enabled and configured and rebooted nothing loads up and when i click on the live tv tab it shows an error saying there is no pvr client enabled, when it is.

Hope this can be fixed.

**Comment by codesnake** [comment]
Just enable needed PVR client manually.

**Comment by kraigtoft** [comment]
i have done that, i think i have sorted it, i was using the aeon nox skin andit wasnt working but i have changed back to confluence and its working again by the looks of things, very strange indeed.

btw thank you for the quick reply. my dvbsky s2 turns up tomorrow, what do you reccomend for the setup, i am connecting it to my sky dish and wanted to get the most channels out of it as possible. not too sure how to configure and what to enable when it comes to the pvr frontend stuff.

many thanks again and your support is top notch

**Comment by codesnake** [comment]
For DVB-S2 you can use tvheadend or vdr

**Comment by kraigtoft** [comment]
thanks alot

**Comment by kraigtoft** [comment]
Hi again

sorry to pick your brain again, i have been to the services and installed the tvheadend, and also enabled the tvheadend client in the pvr section, when i log into my ip address to configure the tvheadend there are no tuners showing up. i tried the tuner in windows and the green power light came on when i installed the driver, but its not coming on when i hook it up to the box, will the driver be missing from openelec. how can i get the driver and also inject it to my box to power on the DVBSky S960 tuner

Thanks again
