### ISSUE TITLE
Building for M8 type Amlogic boxes is broken

### ISSUE THREAD

**Issue by wwortel** [codesnake/OpenELEC.tv#75]
The 'image' script does not produce the zip update because the part that makes the zip has been copied now from original Kodi. It used to do a check on the presence of /install/updater-script and /install/update-binary but it does not do that anymore. Also the path to /install is missing.
The current script still tries to copy these but cannot find them and throws an error.

**Comment by codesnake** [comment]
To build ZIP package you need to issue the following command
```
ARCH=arm PROJECT=Amlogic DEVICE=M8 make amlpkg

**Comment by wwortel** [comment]
Makefile does not know amlpkg so it will not be available as $1 in the image script. Tried amlpkg in the make command but ended up changing the script to get things going. Thanks for giving it your attention.
Another strange thing is the zip signing. My M8 refuses the signature on basis of the current code.
Copied the 'tools' directory from Dec. 2014 version of your code and then it works ....
Don't think the OpenELEC Wetek uses signed zip files for updates so it probably does not get tested there.

**Comment by codesnake** [comment]
What branch you are talking about?

**Comment by wwortel** [comment]
Oooops, sorry looked into wrong Makefile as I have tried several recent OpenELEC.tv versions to get to compile.
To eliminate any further errors started from scratch with today, 20150708, download of codesnake/OpenELEC.tv.
No customizations by me. Needed changes so far to get it to strta to compile:
1. removing in projects/Amlogic/options the mkimage extra dependency (issue reported a few days ago)
2. editing in scripts/image the naming of the build tree on basis of the git version. 
This git stuff does not work when starting from a unzipped .zip download of your code from github.
3. then the compilation stops at compiling amlogic kernel drivers.
  CC      drivers/amlogic/gpu/ump/common/ump_kernel_common.o
armv7a-openelec-linux-gnueabi-gcc-4.9.2: error: directory: No such file or directory
armv7a-openelec-linux-gnueabi-gcc-4.9.2: error: directory": No such file or directory
scripts/Makefile.build:308: recipe for target 'drivers/amlogic/gpu/ump/common/ump_kernel_common.o' failed
make[4]: *** [drivers/amlogic/gpu/ump/common/ump_kernel_common.o] Error 1
scripts/Makefile.build:455: recipe for target 'drivers/amlogic/gpu/ump' failed
make[3]: *** [drivers/amlogic/gpu/ump] Error 2
scripts/Makefile.build:455: recipe for target 'drivers/amlogic' failed
make[2]: *** [drivers/amlogic] Error 2
make[2]: *** Waiting for unfinished jobs....
  CC      fs/squashfs/symlink.o

perhaps more to follow...

**Comment by wwortel** [comment]
Found the cause of the above gpu ump driver error. 000-svn_rev.patch is missing in the project specific linux patches. But is also kernel version specific in what it does. So have reintroduced the patch in /projects/Amlogic/patches/linux and have edited the kernel version number to be 'a9cef51' so that it has an effect.
