### ISSUE TITLE
Matricom MX2 running Openelec 5.0.3 and Kodi14.2

### ISSUE THREAD

**Issue by pknknambiar** [codesnake/OpenELEC.tv#89]
Mouse scroll button does not work. Any solution? suggestion? Many thanks

**Comment by codesnake** [comment]
As far as I know mouse wheel doesn't work in Kodi on any Linux system.

**Comment by pknknambiar** [comment]
Thanks. Is there an Internet Browser facility in any of the latest OpenElec versions? Kindly advise,

**Comment by codesnake** [comment]
No.

**Comment by pknknambiar** [comment]
Thanks for your reply. If there is an add-on like Chrome in Kodi, will it work under OpenElec environment? Kindly advise,

**Comment by codesnake** [comment]
I already answered - no. It will not work in OE for Amlogic boxes.

**Comment by pknknambiar** [comment]
OK. For me as long as Kodi 14.x works with OE on MX2, it is fine. Thanks for replying...

**Comment by pknknambiar** [comment]
Hi,
Kindly advise is there anyway I can install Kodi 15.1 on Matricom MX2
running OpenElec 5.0.3?
Many thanks

*P.K.Nambiar*
