### ISSUE TITLE
Anybody able to update MX2 Gbox past codesnakes 5.03 stable version?

### ISSUE THREAD

**Issue by honeytapper** [codesnake/OpenELEC.tv#99]
I can see openELEC builds upto 5.95.5 but trying to flash the box by network update or sd card have all resulted in failure.Codesnakes releases updates absolutely fine but absolutely no luck with anything after 5.03.Can anybody put me right as I would like to upgrade if its possible?

**Comment by codesnake** [comment]
I will release OE 6.0 shortly.

**Comment by honeytapper** [comment]
Great news and thanks for the reply codesnake.You are doing a great job.
Cheers
